CryptoSignal/Crypto-Signal

README.md
app/app.py

@AbenezerMamo 
I've added my Gmail functionality if you'd like to add it to your project as well. See #11 .

Add email functionality

---

app/analysis.py
app/app.py
app/default-config.json
app/exchange.py
app/logs.py
app/notification.py
app/notifiers/gmail.py
app/notifiers/slack.py
app/notifiers/twilio.py
app/requirements.txt
app/strategies/breakout.py
app/strategies/ichimoku_cloud.py
app/strategies/moving_averages.py
app/strategies/relative_strength_index.py
app/strategies/strategy_utils.py

Added a log helper for configuring logs as either structured (for bot mode) or strings (for user mode).

Add real logging

---

app/analysis.py
app/app.py
app/conf.py
app/default-config.json
app/exchange.py
app/notification.py
app/notifiers/gmail.py
app/strategies/relative_strength_index.py

This extracts the configuration from app.py and moves it to conf.py. Everything can now be configured by env vars instead of just some things. All exchanges are also now supported.
The default-config.json file is now treated kind of like a schema and is mostly considered the source of truth for what the available options are.
This also includes the RSI improvements courtesy of @Lokraan from https://github.com/AbenezerMamo/crypto-signal/pull/39

Extract config

---

Makefile
app/app.py
app/default-config.json
app/notification.py
app/notifiers/integram.py

Added support for notification via integram.org bot to telegram, Add @[integram_bot](https://telegram.me/integram_bot) to telegram, select webhooks and copy URL to config
This fixes AbenezerMamo/crypto-signal#44

Added integram bot notification (Telegram)

---

app/notification.py

The integram merge had a different config setting for notifications, modified to match current master branch layout

Updating Integram Notifier Config Line

---

app/analysis.py
app/app.py
app/behaviour.py
app/behaviours/default.py
app/behaviours/rsi_bot.py
app/conf.py
app/database.py
app/default-config.json
app/exchange.py
app/logs.py
app/strategies/breakout.py
app/strategies/ichimoku_cloud.py
app/strategies/moving_averages.py
app/strategies/relative_strength_index.py
app/strategies/strategy_utils.py

- Uses async with ccxt.async
- Added analysis option in config.
- Removed if statements in strategies.
- Ichimoku cloud only uses one query on bittrex.

Added asynchronous processing and analysis in config.

---

app/analysis.py

Truncate decimals when querying binance

---

app/analysis.py
app/strategies/ichimoku_cloud.py
app/strategies/strategy_utils.py

Ichimoku needs to be calculated from the highs and lows, not just the closes

Ichimoku calculates properly now

---

app/behaviours/default.py
app/behaviours/ui/backtesting/chart.py
app/behaviours/ui/server.py
app/behaviours/ui/www/react/ControlPanel.jsx
app/behaviours/ui/www/react/Dashboard.jsx
app/behaviours/ui/www/react/Plot.jsx
app/behaviours/ui/www/static/index.js
app/behaviours/ui/www/static/templates/index.html
app/exchange.py
docker-compose.yml

- Added an endpoint to grab all available exchanges from ccxt
- Added an endpoint to grab all coin pairs from a given exchange
- Added a dropdown on the UI to select an exchange to grab historical data from
- Added more robust error messages on the UI
- Proper base coin now shows up on the Y-axis label of the graph

Cosmetic endpoints

---

README.md
app/analysis.py
app/behaviour.py
app/behaviours/default.py
app/behaviours/simple_bot.py
app/behaviours/ui/backtesting/chart.py
app/behaviours/ui/backtesting/decision.py
app/behaviours/ui/backtesting/trade.py
app/behaviours/ui/server.py
app/behaviours/ui/www/react/ControlPanel.jsx
app/behaviours/ui/www/react/Plot.jsx
app/behaviours/ui/www/static/index.js
app/conf.py
app/default-config.json
app/exchange.py
app/requirements.txt
app/strategies/breakout.py
docker-compose.reporter.yml

- Plot on the UI will no longer display data points for indicators with insufficient data (i.e., don't plot the first 9 data points for the SMA9 indicator, etc.)
- Buys and sells will not be made if indicators do not have sufficient data (this also handles NaN's within the Decision() class)

Fixed Backtesting Decision Buy (Issue # 102)

---

app/analysis.py
app/behaviours/default.py
app/behaviours/simple_bot.py
app/exchange.py

This is not ready for merging yet as it requires testing... however this makes some good cleanliness changes that enable retries by default on all ccxt requests.

Change retries remove historical data from analyzer

---

app/conf.py
app/exchange.py
app/notifiers/gmail_client.py
docker-compose.reporter.yml

Fixes reporter crashing when BTC is the base currency.

Reporter crash on btc base

---

app/behaviours/simple_bot.py
app/conf.py
app/database.py
app/db/transactions.py
app/default-config.json
app/exchange.py
app/notifiers/gmail_client.py
docker-compose.reporter.yml

Add a 24 hour trade limit on the volume of BTC the bot can trade.

Add daily btc limit

---

app/behaviours/simple_bot.py
app/conf.py
app/database.py
app/db/transactions.py
app/default-config.json
app/exchange.py
app/notifiers/gmail_client.py
docker-compose.reporter.yml

Allows the ability to configure specific quote currencies to ignore.

Ignore specific quotes

---

app/behaviours/simple_bot.py
app/conf.py
app/database.py
app/db/transactions.py
app/default-config.json
app/exchange.py
app/notifiers/gmail_client.py
docker-compose.reporter.yml

Adds the ability to specify a trade minimum for simple bot.

Min trade value

---

app/behaviours/simple_bot.py
app/default-config.json
app/exchange.py

Allows you to set a minimum daily BTC volume before initiating a buy.

btc min volume

---

app/behaviours/reporter.py
app/behaviours/simple_bot.py
app/database.py
app/default-config.json
app/exchange.py

Fixes the bug of the reporter not reporting on all pair changes.

Fix reporter bug

---

app/analysis.py

Didn't think there should be two in a row .. ? Just poking around

Removed duplicate dataframe / transpose

---

Makefile
app/behaviours/simple_bot.py
app/default-config.json

Allows the specification of multiple indicators for buying and selling.

Composite indicators

---

.gitignore
README.md
docker-compose.yml

Changes docker-compose file from .env to settings.env so that windows users have an easier time

Changed .env file for windows users

---

app/behaviour.py

Moved the try catch block such that it will skip information for the pair if it fails to fetch information for an analysis instead of showing empty data.

Move try/catch so that it skips the pair.

---

app/exchange.py

even more betterer

---

README.md
app/behaviour.py
app/exchange.py

Reorganize

---

app/conf.py

Fixes an issue where json list objects were not properly being assigned to config dict.

Fix config error

---

app/analysis.py
app/conf.py
app/indicators/__init__.py
app/indicators/stoch_rsi.py
docs/config.md

Add stochastic RSI

---

app/analysis.py
app/conf.py
app/indicators/ema.py
app/indicators/sma.py

Implementation of SMA and EMA crossovers. Indicator is hot when the faster moving average crosses over the slower moving average in the latest candlestick, and is cold when the faster moving average dips below the slower moving average in the latest candlestick

SMA and EMA crossovers

---

app/behaviour.py
app/conf.py
app/indicators/ema.py
app/indicators/sma.py
docs/config.md

Multiple indicators

---

app/behaviour.py
app/notification.py

https://github.com/CryptoSignal/crypto-signal/issues/227

[#227] don't send notification if message is empty or only contains whitespaces

---

app/behaviour.py
app/conf.py
app/exchange.py
app/indicators/analyzers/utils.py
app/indicators/bollinger_bands.py
app/indicators/ema.py
app/indicators/macd.py
app/indicators/momentum.py
app/indicators/rsi.py
app/indicators/sma.py
app/indicators/stoch_rsi.py
app/indicators/utils.py
app/notification.py
app/notifiers/gmail_client.py
app/notifiers/utils.py
app/requirements.txt
docs/config.md

I still need to write documentation so not merge-able yet.
This implements templatable messaging as well as stateful notifications

Custom message templating

---

app/notification.py

Fix alerts not being disabled

---

app/analysis.py
app/conf.py
app/indicators/__init__.py
app/indicators/mfi.py

Implement MFI from ta-lib

---

app/conf.py
app/indicators/stoch_rsi.py
app/indicators/utils.py

This changes stoch RSI to a custom implementation instead of relying on TA-lib.
This does not implement an EMA on Fast K. I don't know if that is a behaviour people would expect or not...

Fix stoch RSI

---

README.md
app/analysis.py
app/conf.py
app/indicators/__init__.py
app/indicators/vwap.py

Added VWAP indicator

---

app/analyzers/indicators/macd.py
app/analyzers/indicators/stoch_rsi.py
app/conf.py
app/notification.py
app/notifiers/twilio_client.py
app/notifiers/webhook_client.py
app/requirements.txt
docs/config.md

Discord was not being enabled correctly.

Fix discord bug

---

app/analyzers/indicators/ichimoku.py
app/analyzers/indicators/macd.py
app/analyzers/indicators/stoch_rsi.py
app/analyzers/informants/vwap.py
app/conf.py
app/notification.py
app/notifiers/twilio_client.py
app/notifiers/webhook_client.py
app/outputs.py
app/requirements.txt
docs/config.md

JSON output now has more complete information about the configuration of the indicator.

Fix json output

---

app/analyzers/indicators/ichimoku.py
app/analyzers/indicators/macd.py
app/analyzers/indicators/stoch_rsi.py
app/analyzers/informants/vwap.py
app/behaviour.py
app/conf.py
app/notification.py
app/notifiers/twilio_client.py
app/notifiers/webhook_client.py
app/outputs.py
app/requirements.txt
docs/config.md

Corrects attempting to output when there are no results.

Fix output error

---

Makefile

for my docker version i need an absolute path

fix path for make run

---

Makefile
README.md
app/analyzers/informants/bollinger_bands.py

Fixes the orientation of the bollinger bands data

fix bb data

---

.gitignore
app/defaults.yml
app/notification.py
app/notifiers/stdout_client.py
docs/config.md

This will just print out the message to stdout.
Useful for testing

 simple notification to stdout. Useful for testing 

---

app/notification.py

sorry about the merge I forgot a function

fix stdout

---

app/analysis.py
app/analyzers/indicators/__init__.py
app/analyzers/indicators/bollinger.py
app/behaviour.py

Check when close price crosses the Upper/Lower bands.

Bollinger Bands Indicator

---

app/analyzers/indicators/ichimoku.py
app/notification.py

1. Ichimuko analysis
- changed analysis calculation
- takes into account cloud offset of senkou span in dataframe (26 time period) 
- compares data across dates now instead of dataframe index
2. Added Ichimuko chart creation

Ichimuko analysis+chart

---

README.md
app/analysis.py
app/analyzers/indicators/__init__.py
app/analyzers/indicators/adx.py
docs/config.md

**Description**
The Average Directional Movement Index (ADX)  is designed to quantify trend strength by measuring the amount of  price movement in a single direction. The ADX is part of the Directional Movement  system published by J. Welles Wilder, and is the average resulting from the Directional Movement indicators.
0-25    absent or weak trend
25-50   strong trend
50-75   very strong trend
75-100  extremely strong trend

Addding ADX(Average Directional Index) indicator

---

README.md
app/analysis.py
app/analyzers/indicators/__init__.py
app/analyzers/indicators/klinger_oscillator.py
app/behaviour.py
app/requirements-step-2.txt
docs/config.md

A volume-based indicator, which assists traders to identify a longer-term view of price trends.

Klinger Oscillator

---

README.md
app/analysis.py
app/analyzers/indicators/__init__.py
app/analyzers/indicators/candle_recognition.py
app/behaviour.py
app/notification.py
app/outputs.py

Uses Ta-lib for candle pattern recognition and allows coloring of candles for chart

Candle recognition

---

.gitignore
README.md
app/analyzers/indicators/ichimoku.py
app/behaviour.py
app/notification.py

Updated Ichimoku
- Added Chikou span
- Added the ability to create custom strategies

Ichimoku update
